### ISSUE TITLE
Possible WebExtension support

### ISSUE THREAD

**Issue by MOFTAD** [rNeomy/clean-uninstall#10]
Hello, do you plan on converting this add-on into a WebExtension in preparation for Mozilla's upcoming changes in Firefox 57? Is it even possible given the level of functionality granted by WEs?

Thank you for reading.

**Comment by Taurean75** [comment]
I'd also like to know. Thanks.

**Comment by ghost** [comment]
+1 Please convert to WebExtension if possible, thanks.

**Comment by yfdyh000** [comment]
I think it is impossible and no longer needed, WebExtensions no APIs to read and write to preferences and files.

**Comment by rNeomy** [comment]
True. there will be no need for this extension when there is no legacy support. This is basically the end of Clean Uninstall :)
