### ISSUE TITLE
Clean Uninstall opens after disabling an add-on

### ISSUE THREAD

**Issue by maxoku** [rNeomy/clean-uninstall#11]
It's annoying when Clean uninstall is trying to clean settings of an add-on I just disabled. And it also has problems to work when I remove a disabled add-on. It should recognize exactly when I'm removing the add-on regardless if it's enabled or disabled and also shouldn't do anything when only disabling add-on, not removing.

**Comment by rNeomy** [comment]
will be fixed on the next release. Thanks for the report.
