### ISSUE TITLE
Clean Uninstall/Open Cleaner shows an entry that doesn't exist

### ISSUE THREAD

**Issue by REVerdi** [rNeomy/clean-uninstall#2]
Clean Uninstall/Open Cleaner shows

![noname](https://cloud.githubusercontent.com/assets/618482/13730876/cdcaf106-e93a-11e5-9888-c2ca5c1c890d.png)

but in about:config does NOT exist {D9A7CBEC-DE1A-444f-A092-844461596C4D} ([Default Full Zoom Level](http://www.systemlookup.com/FF_Extensions/677-Default_Full_Zoom_Level.html)). What are these six preferences?

**Comment by rNeomy** [comment]
That's definitely a bug, most likely the branch belongs to Firefox itself. Just ignore it till next version. Thanks for the report.

**Comment by rNeomy** [comment]
Please confirm https://github.com/rNeomy/clean-uninstall/blob/master/builds/jid1-gjJqQ12bh0olrR@jetpack-0.1.5b1.xpi?raw=true does not display the branch

**Comment by REVerdi** [comment]
Yes, it worked! The branch was not displayed. Thank you very much for the support.
