### ISSUE TITLE
Open Cleaner button does not work

### ISSUE THREAD

**Issue by MOFTAD** [rNeomy/clean-uninstall#3]
Same problem as robzuc from the site's discussion section - the open cleaner button does nothing. I followed your instructions (clearing console, disabling and re-enabling add-on). Here is the console: http://i.imgur.com/IRMLnHv.png. 

FF 45.0.1
Latest version of the add-on

Edit: Turns out it opens if I access the add-on's options from the about:addons page. I had been attempting to use it in my sidebar. I guess it's a separate bug, then - it doesn't work when accessed from a sidebar.

**Comment by MacgyverJohnson** [comment]
Same here with same firefox version ........not working with omni sidebar....pls make it compatible with sidebars TIA
Other than that its working great......is it true that from ff48 this addon will be able to differentiate between addon disabling and uninstalling?
