### ISSUE TITLE
I'd like to be compatible with Firefox's fork version

### ISSUE THREAD

**Issue by Shitennouji** [rNeomy/clean-uninstall#7]
I use Pale Moon, Firefox, SeaMonkey respectively.
I would like to use this excellent add-on in those fork versions.
I would like to ask compatibility correspondence by all means.

**Comment by Shitennouji** [comment]
I confirmed the update (0.1.9).
Immediately, it implemented in Pale-Moon 27.3.0 (32-bit).
Thank you very much.

**I have a request.
Please also Thunderbird !**

**Comment by rNeomy** [comment]
We are supporting PM. Thunderbird does not support SDK and hence there is no way to make this compatible.

**Comment by Shitennouji** [comment]
OK!
